[unstable]
build-std-features = ["compiler-builtins-mem"] # for necessary c functions
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rOSt.json"

# allows for cargo run to compile kernel and boot it in QEMU
[target.'cfg(target_os = "none")']
runner = "bootimage runner"